const { cmd } = require('../command');
const axios = require('axios');

cmd({
    pattern: "img",
    alias: ["image", "unsplash"],
    react: '📸',
    category: "search",
    desc: "Search high-quality images from Unsplash",
    filename: __filename
}, async (robin, m, mek, { from, q, reply }) => { // Changed parameter names to match framework
    try {
        if (!q) return await reply("❌ Please provide a search term (e.g., .img nature)");

        await reply(`🔍 Searching Unsplash for *${q}*...`);

        // Unsplash API
        const UNSPLASH_KEY = "Ii2PCyEiA4gqrHdXKBQ9PaewWGMGiWMoA3XO4PtLaEI";
        const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(q)}&per_page=5&client_id=${UNSPLASH_KEY}`;

        const { data } = await axios.get(url);
        const images = data.results;

        if (!images.length) return await reply("❌ No images found!");

        // Send images
        for (const img of images) {
            await robin.sendMessage(from, { // Changed from sock to robin
                image: { url: img.urls.regular },
                caption: `📷 *${q}*\n\nPhoto by ${img.user.name} \n\n> Generated by CYBERX-AI `
            }, { quoted: mek });
            await new Promise(resolve => setTimeout(resolve, 500));
        }

    } catch (error) {
        console.error("Unsplash Error:", error);
        await reply("❌ Error fetching images. Try again later.");
    }
});
